# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow checks out code, performs a Codacy security scan
# and integrates the results with the
# GitHub Advanced Security code scanning feature.  For more information on
# the Codacy security scan action usage and parameters, see
# https://github.com/codacy/codacy-analysis-cli-action.
# For more information on Codacy Analysis CLI in general, see
# https://github.com/codacy/codacy-analysis-cli.

name: Codacy Security Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "develop" ]
  schedule:
    - cron: '31 6 * * 4'

permissions:
  contents: read

jobs:
  security-scan:
    name: Codacy Security Scan
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: [javascript, python, java, ruby]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Environment
        run: |
          echo "Setting up for ${{ matrix.language }} analysis"
          # Tambahkan setup spesifik bahasa di sini

      - name: Run Codacy Analysis
        uses: codacy/codacy-analysis-cli-action@v4.1.0
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          output: results-${{ matrix.language }}.sarif
          format: sarif
          # Sesuaikan tools berdasarkan bahasa
          tools: ${{ matrix.language == 'javascript' && 'eslint' || matrix.language == 'python' && 'bandit' || matrix.language == 'java' && 'spotbugs' || 'brakeman' }}

      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results-${{ matrix.language }}.sarif
